dist: bionic
sudo: required
language: python
python:
  - "3.7"

addons:
 apt:
   packages:
     - libhdf5-dev
     - hdf5-tools

env:
 - PYTHONPATH=$PYTHONPATH:$(pwd)/build/stage/lib/ && PY_EXE=$(which python)

jobs:
    include:
    - name: CMake
      before_script:
          - python -V
          - pip install pytest numpy
          - pip install h5py
          - pip install numba
          - pip install scipy
          - pip install git+https://gitlab.com/reinholdt/polarizationsolver.git@master
          - mkdir build
          - cd build
          - cmake -DBUILD_SHARED_LIBS=on -DENABLE_PYTHON_INTERFACE=ON -DPYTHON_EXECUTABLE=$PY_EXE ..

      script:
          - cmake --version
          - make
          - cd ..
          - pytest
    - name: Setuptools
      before_script:
          - pip install git+https://gitlab.com/reinholdt/polarizationsolver.git@master
      script: python setup.py test
